
services:
  - type: web
    name: facesync
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true

